services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-/api}
      - REACT_APP_SOCKET_URL=${REACT_APP_SOCKET_URL:-/}
      - REACT_APP_VERSION=${REACT_APP_VERSION:-1.0.0}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  frontend_data: 