services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/promobot
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-seu_jwt_secret}
      - PORT=3001
      - REDIS_URL=redis://redis:6379
      - REDIS_ENABLED=true
      - EVOLUTION_API_URL=${EVOLUTION_API_URL:-http://evolution-api:8080}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY:-sua_api_key}
      - WHATSAPP_INSTANCE=${WHATSAPP_INSTANCE:-PromoBot}
    volumes:
      - api_logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
  mongo_data:
  api_logs: 